# Generated by Django 5.2.3 on 2025-07-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate_only',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='certificate_only',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='certificate_only',
            name='cert_only_link',
            field=models.URLField(max_length=1000),
        ),
    ]
